services:
  database:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: book_connector_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - book_connector_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d book_connector_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - book_connector_net
    env_file:
      - .env

volumes:
  postgres_data:
    driver: local

networks:
  book_connector_net:
    driver: bridge